use_frameworks!

target 'NDHBiometricHelper_Example' do
  pod 'NDHBiometricHelper', :path => '../'

  target 'NDHBiometricHelper_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
